### ISSUE TITLE
Additional information about exercise and and exam question clarification

### ISSUE THREAD

**Issue by eLi1a** [santikka/R-course#3]
Hi! 
I'm a student from UEF, thank you for your hard work for creating the Rcourse package! I just finished the course today and would like to suggest additional information for the questions that confused me.

(The following questions are loaded from the sysdata.rda in /R repo )

`english_questions[["Section 8"]][["3"]]`
Find the root of the function exp(x + 4) + 3*x. Answer with the accuracy of two decimals. Use the function
'uniroot'.
add interval information to the EN question to match the answer
-->
"Find the root of the function exp(x + 4) + 3*x on interval (-3, 2). Answer with the accuracy of two decimals. Use the function
'uniroot'."

`exam_questions_uef[["1"]]`
"Read in the data from the file PISA_value.txt into the variable pisa."
--> 
"Read in the data from the file PISA_value.txt into the variable pisa,  and read the PISA_variables.PDF downloaded from eLEARN."
This would help to remind the students to review the variable details, and also provide insight for the question related to factors; for me, pisa is loaded as all numeric values, thus in question 9 I was confused about the category city, because when I run "unique(pisa_ori$urban) , output: 1 2 ", and had the same confusion about gender assignments, but the categorical value shows after the question of creating "f" columns.

`exam_questions_uef[["12"]]`
correct level amount of variable region
--> 
  "Modify the PISA data by adding three new variables with the following names and order:
  fgender, furban and fregion. The variables should be added as the last columns of the data table.
  They should correspond to the existing variables ST04Q01, urban and region, as well as be in a factor form.
  Name the levels of the factors according to the file PISA_variables.pdf found from the course page
  (The variable ST04Q01 has two levels, as well as the variable urban, but the variable region **has four levels.**
  Also, pay attention to the lower case and upper case letters in the level names).
  Keep in mind that there are no observations from Åland (Ahvenanmaa). 
  Assign the modified data into the variable pisa."

Additionally, maybe the PDF can also be updated: `"region region 1 = Southern Finland, 2 = Western Finland, 3 = Eastern Finland, 4 = Northern Finland, 5 = Åland " to remove "5 = Åland"`, since it doesn't appear in the dataset, but I understand that may cause additional correctiona in the exam questions.

Again, thank you for the interesting course! 
Wish you have a delightful summer :)

**Comment by santikka** [comment]
Thanks for the feedback @1eeGit !

The interval is arbitrary for the root-finding question, as long as the interval contains the root. (-3, 2) is just an example used in the solution, similar to other problems involving roots.

Adding a reference to the PISA_variables.pdf and clarifying the factor question are good ideas. I'll implement these in the next version of the package.

EDIT: The factor question does expect five levels, but perhaphs it would be more intuitive to remove the fifth level.

**Comment by eLi1a** [comment]
Thank you for your reply! 
I understand the interval setting now. :)
